# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
    v.gui = true
  end
  config.vm.box_check_update = false
  config.vm.define "development" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.synced_folder "/workspace", "/workspace", create: true
    node.vm.network :forwarded_port, guest: 8080, host: 8080
    node.vm.network :forwarded_port, guest: 80, host: 8888
    node.vm.network :forwarded_port, guest: 4546, host: 4546
    node.vm.network :forwarded_port, guest: 2525, host: 2525
    node.vm.network :forwarded_port, guest: 1521, host: 1521
    node.vm.network :forwarded_port, guest: 9000, host: 9000
	node.vm.network :forwarded_port, guest: 8500, host: 8500

    node.vm.provision "bootstrap", type: "shell" do |s|
      s.privileged = false
    	s.path = "../provision.sh"
    end
    node.vm.provision "ansible", type: "shell" do |s|
      s.privileged = false
    	s.path = "../ansible.sh"
    end
  end
end