---
ruby_library_version:   "2.0.0"
ruby_version:           "ruby-2.0.0-p598"
ruby_checksum:          "4136bf7d764cbcc1c7da2824ed2826c3550f2b62af673c79ddbf9049b12095fd"
ruby_download_location: "http://cache.ruby-lang.org/pub/ruby/2.0/{{ ruby_version }}.tar.gz"
ruby_bundler_flags: "--no-document"

ruby_apt_dependencies:
  - libreadline-dev
  - libssl-dev
  - libyaml-dev
  - zlib1g-dev

ruby_yum_dependencies:
  - readline-devel
  - openssl-devel
  - libyaml-devel
  - zlib-devel

ruby_symlinks:
  - bundle
  - erb
  - gem
  - irb
  - rake
  - rdoc
  - ri
  - ruby
  - testrb
  - cucumber

ruby_location: "/opt/{{ ruby_version }}"

ruby_executable: "{{ ruby_location }}/bin/ruby"
